version: "3.8"
services:
  mongo:
    image: mongo:4.2.10
    container_name: mongo
    restart: always
    ports:
      - 27017:27017

    volumes:
      - $HOME/mongo:/data/db
    healthcheck:
      test: "exit 0"

  spring-api:
    container_name: smdc-crud-spring-api
    build: .
    image: spring-api
    depends_on:
      - mongo

    hostname: localhost
    restart: always
    ports:
      - 8088:8088
    healthcheck:
      test: "exit 0"